Deprecate middleware listener
laminas/laminas-mvc pull request #51
Opened 2020-05-03 18:07 UTC by Xerkus

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description
- Bump php to ^7.2.
- Deprecate MiddlewareListener and point to laminas/laminas-mvc-middleware

2020-06-09 09:01 UTC, Xerkus commented on docs/book/middleware.md
> +[laminas-mvc-middleware](https://github.com/laminas/laminas-mvc-middleware)
This should probably link to the docs page

2020-06-09 09:12 UTC, froschdesign commented on docs/book/middleware.md
> +laminas-mvc application to function.
We can added a page with instructions for installations in the documentation of laminas-mvc-middleware which covers the module registration.

An example can be found in the documentation of laminas-i18n:

* Page in docs: https://docs.laminas.dev/laminas-i18n/installation/
* Configuration: https://github.com/laminas/laminas-i18n/blob/327fdc2d07572e273f8122f46b52c7475a730826/mkdocs.yml#L48-L52

The link can then be added here.

2020-06-09 10:33 UTC, Xerkus commented
@froschdesign I updated the middleware documentation page to directs to laminas-mvc-middleware. Existing documentation for the feature is dropped here since it was extracted along with the code into laminas-mvc-middleware.
I believe this approach is better and less confusing.

2020-12-14 20:55 UTC, weierophinney requested changes
Makes sense! I've made some suggestions from a native-English speaker point of view related to grammar.

2020-12-14 20:55 UTC, weierophinney commented on docs/book/middleware.md
> +request handlers for the route matches that contain a `middleware` parameter.
```suggestion
The package [laminas-mvc-middleware][laminas-mvc-middleware] is a laminas-mvc
application module that enables dispatching of middleware, middleware pipes, and
request handlers for route matches that contain a `middleware` parameter.
```

2020-12-14 20:55 UTC, weierophinney commented on docs/book/middleware.md
> +laminas-mvc application.
```suggestion
With version 2.7.0, laminas-mvc began offering the now deprecated
`Laminas\Mvc\MiddlewareListener`. The `MiddlewareListener` is always enabled, but
requires optional dependencies installed to be used.  
A new laminas-mvc module, [laminas-mvc-middleware][laminas-mvc-middleware], transparently replaces
it with `Laminas\Mvc\Middleware\MiddlewareListener` when registered with a
laminas-mvc application.
```

2020-12-14 20:55 UTC, weierophinney commented on docs/book/middleware.md
> +`middleware` parameter.
```suggestion
Starting with version 3.2.0, the built-in `Laminas\Mvc\MiddlewareListener` will
trigger deprecation level errors on any attempt to handle a route match containing
a `middleware` parameter.
```

2020-12-14 20:55 UTC, weierophinney commented on docs/book/middleware.md
> +application.
```suggestion
If your application currently depends on the built-in optional middleware
support, `laminas/laminas-mvc-middleware:~1.0.0` provides a drop-in replacement.
If you use this new module, please note that the module `Laminas\Mvc\Middleware`
must be enabled in your laminas-mvc application.
```

2020-12-14 20:55 UTC, weierophinney commented on src/MiddlewareListener.php
> +            . ' please use laminas/laminas-mvc-middleware package instead',
```suggestion
            . ' please use the laminas/laminas-mvc-middleware package instead',
```

2020-12-14 21:05 UTC, Xerkus commented on test/MiddlewareListenerTest.php
> +        $this->expectDeprecationMessage('use laminas/laminas-mvc-middleware');
For suggested wording changes test expectation needs to be updated as well
```suggestion
        $this->expectDeprecationMessage('use the laminas/laminas-mvc-middleware package');
```

2020-12-14 21:14 UTC, weierophinney approved these changes

2020-12-14 21:20 UTC, merged